---
title: "Decompositional Methods for Indian TV Ratings"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2) 
library(forecast)
library(tis)

# Read CSV into R
setwd("/Users/davidleonardi/Projects/Indian_TV_Time_Series")
curDir <- getwd()
```
Load Data. 
```{r}
df <- read.csv(file="./data/ActualRatings_weeklyGRP.csv", header=TRUE, sep=",", stringsAsFactors=FALSE)

# remove extra column
df <- df[ , !(names(df) %in% c("X"))]

# convert string date to R POSIXct format
df$GRPRatingsDate <- as.POSIXct(as.Date(sapply(df$GRPRatingsDate, function(x) strsplit(x, " ")[[1]][1]), "%d-%B-%Y"))
```
Plot Data.
```{r}
ggplot(data=df, aes(x=GRPRatingsDate, y=GRP)) +
  geom_line()+
  geom_point()+
  labs(title="Weekly Ratings 2007 - 2009", y="GRP", x="GRP Ratings Date")
```

Split data to training and testing data.

```{r}
df_train <- df[which(df$GRPRatingsDate <= "2008-10-26"),]
df_test <- df[which(df$GRPRatingsDate > "2008-10-26"),]

head(df_train, 5)
```

```{r}
head(df_test, 5)
```

### Decompose the data
#### Using decompose method

```{r}
timeseries_train = `^`(df_train$GRP, 0.7)

ts_train = ts(timeseries_train, frequency = 12)

decompose_train_additive = decompose(ts_train, "additive")
plot(decompose_train_additive)
```

```{r}
decompose_train_multiplicative = decompose(ts_train, "multiplicative")
plot(decompose_train_multiplicative)
```

#### Using STL

```{r}
stl_train = stl(ts_train, s.window="periodic")
seasonal_stl_train <- stl_train$time.series[,1]
trend_stl_train <- stl_train$time.series[,2]
random_stl_train <- stl_train$time.series[,3]

plot(as.ts(seasonal_stl_train))
```
```{r}
plot(trend_stl_train)
```

```{r}
plot(random_stl_train)
```

```{r}
plot(stl_train, main="Seasonal Decomposition of Time Series by Loess (STL)")
```

```{r}
ts_train_actual <- ts(df_train$GRP, frequency = 12)
ts_train_predicted <- ts(`^`(stl_train$time.series[,1]+stl_train$time.series[,2], 1/0.7), frequency = 12)
```

```{r}
forecast_stl <- forecast(stl_train, h=21)
plot(forecast_stl)
```
```{r}
unclass(forecast_stl)
```

```{r}
ts_test_actual <- ts(df_test$GRP, frequency = 12)
ts_test_predicted <- ts(`^`(forecast_stl$mean, 1/0.7), frequency = 12)
```

```{r}
train_mape <- Reduce(`+`, unclass(abs((ts_train_actual-ts_train_predicted)/ts_train_actual) * 100)) / length(ts_train_actual)
cat("Train MAPE:",train_mape,"%")
```

```{r}
train_mae <- Reduce(`+`, unclass(abs(ts_train_actual-ts_train_predicted))) / length(ts_train_actual)
cat("Test MAE:",train_mae)
```

```{r}
test_mape <- Reduce(`+`, unclass(abs((ts_test_actual-ts_test_predicted)/ts_test_actual) * 100)) / length(ts_test_actual)
cat("Test MAPE:",test_mape,"%")
```

```{r}
test_mae <- Reduce(`+`, unclass(abs(ts_test_actual-ts_test_predicted))) / length(ts_test_actual)
cat("Test MAE:",test_mae)
```



```{r}
new_df <- ts(df_train$GRP, start = c(2007,23), frequency = 52)
new_df
```

```{r}
decompose_df <- tslm(new_df ~ trend + fourier(new_df, 2))
decompose_df
```

```{r}
trend <- coef(decompose_df)[1] + coef(decompose_df)['trend'] * seq_along(new_df)

components <- cbind(
  time.series = cbind(
    data = new_df,
    seasonal = new_df - trend - residuals(decompose_df),
    trend = trend,
    remainder = residuals(decompose_df)
  )
)
plot(components)
```

```{r}
forecast_stl <- forecast(components, h=21)
plot(forecast_stl)
```
```{r}
stl_train
```

```{r}
components
```